apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwebui
  namespace: openwebui
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ai.ryandev.ru`)
      kind: Rule
      services:
        - name: openwebui
          port: 8080
  tls:
    secretName: ai-ryandev-ru-tls
