apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data
  namespace: openwebui
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
