apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/part-of: infra
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
        app.kubernetes.io/name: matter-server
        app.kubernetes.io/part-of: infra
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: infra-master
      containers:
        - name: matter-server
          image: ghcr.io/matter-js/python-matter-server:stable
          imagePullPolicy: IfNotPresent
          args:
            - --storage-path
            - /data
            - --paa-root-cert-dir
            - /data/credentials
          ports:
            - name: websocket
              containerPort: 5580
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 768Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matter-server-data
