apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/part-of: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
