apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/part-of: infra
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: matter-server
  ports:
    - name: websocket
      protocol: TCP
      port: 5580
      targetPort: websocket
