apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      replicas: 1
    service:
      type: LoadBalancer
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
