apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: infra
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information

    listener 1883 0.0.0.0
    allow_anonymous true
