apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
