apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: infra
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
