apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ryandev-ru
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: infra
spec:
  secretName: argocd-ryandev-ru-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd.ryandev.ru
  privateKey:
    rotationPolicy: Always
