apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/part-of: infra
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: homeassistant
