apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ryantrue/infra.git
    targetRevision: main
    path: apps/mosquitto
  destination:
    server: https://kubernetes.default.svc
    namespace: mosquitto
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
