apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-routes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ryantrue/infra.git
    targetRevision: main
    path: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
