apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 40.2.0
    helm:
      releaseName: traefik
      valuesObject:
        api:
          dashboard: true
        deployment:
          replicas: 1
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
        service:
          type: NodePort
        ports:
          web:
            nodePort: 30080
          websecure:
            nodePort: 30443
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
