apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
        - name: collabora
          image: collabora/code:latest
          ports:
            - name: http
              containerPort: 9980
          env:
            - name: domain
              value: cloud\\.ryandev\\.ru
            - name: server_name
              value: office.ryandev.ru
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 2Gi
